### ISSUE TITLE
some nums to motivate?

### ISSUE THREAD

**Issue by timm** [ai-se/Vivek-Prelims#1]
> "How can we run EA on budget?We have seen how EAs can be very useful in solving problems withrelative ease and bare minimum knowledge about the domain. ButEAs have been plagued with the problems of slow convergence andrequiring a lot of function evaluations. "

if you had some numbers here, or a table, or a bar chart, of the time required to run all those config options ,that would strongly motivate this section

**Comment by vivekaxl** [comment]
![screenshot 2016-04-04 10 05 03](https://cloud.githubusercontent.com/assets/6147456/14250907/788efa00-fa4e-11e5-8d68-758c43b018f1.png)
added
