### ISSUE TITLE
(a little) more on surrogate modeling

### ISSUE THREAD

**Issue by timm** [ai-se/Vivek-Prelims#2]
the following does not say how our works fits into the general surrogate stuff. any why we are not using those techniques. and which of the following would be promising for us in future work? e.g i'd like to know more about  Central Composite Design(CCD) [38], Orthogonal Array Sampling (OAS) [38]

> 2.2.1    Componets of a Surrogate ModelSurrogate  Models  can  be  build  primarily  using  a  combinationof two techniques: Machine Learning techniques which uses tech-niques like polynomial functions [31],  Kriging models [32],  Ra-dial Basis Functions (RBFs) [33],  Multivariate Adaptive Regres-sion Splines (MARS) [34], Neural Networks [35] and Support Vec-tor Regression (SVR) [36]. To learn from the given data points thelearners need samples which is provided by a host of sampling al-gorithms.  Sampling techniques primarily used in the literature areLatin Hypercube Sampling (LHS) [37], Central Composite Design(CCD) [38], Orthogonal Array Sampling (OAS) [38] and Full Fac-torial Sampling (FFS) [38]. For more details refer to [17]
> 
> .2.2    Classifications in Surrogate ModelsSurrogate methods can be divided into two general frameworksbased on the classiciation described in [39] and [40].  The classifi-cation is based on when the surrogate model is updated.  The twomain classes areSequential: The key point in sequential framework is to buildthe surrogate model first and then apply the optimizer.  Se-quential mode of surrogates are used in [41–45] among manyothersAdaptive:  The points sampled in the initial pass (before op-timization) may not have points which are representative ofPareto  Front.   To  overcome  this  shortcoming  this  mode  ofSurrogates are updated in each generation by selecting pointssuch that accuracy of the model stays in admissable range.Adaptive mode of surrogates were used in [46–49] amongmany othersThe general methods to assess the quality of the models are: RMSE,PRedicted Error Sum of Squares (PRESS) [50], cross-validation [51]andR2[52].  Other papers worth mentioning are work by Lim etal., which proposed online weighted average ensemble of surrogatemethods [53], Zhou et al. which proposed to use a global model tofind promising points and then use local models to guide memeticsearch [54], Ong et al.  which makes a statement how uncertainityof a surrogate model can be a blessing in disguise and why highlyaccurate model is not required

**Comment by vivekaxl** [comment]
Added some details about the sampling methods.
